[project]
name = "riskguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.6",
    "django-htmx>=1.27.0",
    "django-json-widget>=2.1.1",
    "django-tailwind[cookiecutter,honcho,reload]>=4.5.0",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
]
