# Generated by Django 6.0.6 on 2026-07-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence Client')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('siret', models.CharField(max_length=14, unique=True, verbose_name='Numéro SIRET')),
                ('business_line', models.CharField(max_length=100, verbose_name="Secteur d'activité")),
                ('is_active', models.BooleanField(default=True, verbose_name='Client actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_clients', to=settings.AUTH_USER_MODEL, verbose_name='Modifié en dernier par')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
