# Generated by Django 6.0.6 on 2026-07-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inspection Zone'),
        ),
    ]
