# Generated by Django 6.0.6 on 2026-07-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_company_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reference',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence Société'),
        ),
    ]
