# Generated by Django 6.0.6 on 2026-07-10 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_company_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size_category',
            field=models.CharField(default='', max_length=100, verbose_name='Catégorie taille de société'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='executive_board',
            field=models.TextField(default='', verbose_name="Conseil d'administration"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='labels',
            field=models.TextField(default='', verbose_name='Certifications et labels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='legal_structure',
            field=models.CharField(default='', max_length=100, verbose_name='Structure juridique'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='nb_employees',
            field=models.IntegerField(default=500, verbose_name="Nombre d'employés"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='siren',
            field=models.CharField(default='', max_length=9, verbose_name='Numéro SIREN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(default='', max_length=20, verbose_name='Numéro de TVA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(default='', verbose_name='Site web'),
            preserve_default=False,
        ),
    ]
