# Generated by Django 6.0.6 on 2026-07-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='executive_board',
            field=models.TextField(blank=True, verbose_name="Conseil d'administration"),
        ),
        migrations.AlterField(
            model_name='company',
            name='labels',
            field=models.TextField(blank=True, verbose_name='Certifications et labels'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_structure',
            field=models.CharField(blank=True, max_length=100, verbose_name='Structure juridique'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nb_employees',
            field=models.IntegerField(blank=True, verbose_name="Nombre d'employés"),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de TVA'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_fix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone fixe'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number_mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone mobile'),
        ),
    ]
