# Generated by Django 6.0.6 on 2026-07-03 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('schema', models.JSONField(verbose_name='Schéma du formulaire (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Modèle de visite',
                'verbose_name_plural': 'Modèles de visite',
            },
        ),
        migrations.CreateModel(
            name='InspectionFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence du dossier')),
                ('current_phase', models.CharField(choices=[('CREATION', 'En création'), ('ASSIGNED', 'Assigné / Planifié'), ('IN_PROGRESS', 'Dossier en cours'), ('REVIEW', 'En cours de revue'), ('COMPLETED', 'Terminé / Clôturé'), ('ARCHIVED', 'Archivé')], default='CREATION', max_length=20, verbose_name='Phase actuelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dossier actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_folders', to='crm.Company', verbose_name='Société')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_folders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_folders', to=settings.AUTH_USER_MODEL, verbose_name='Modifié en dernier par')),
            ],
            options={
                'verbose_name': "Dossier d'inspection",
                'verbose_name_plural': "Dossiers d'inspection",
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données saisies (JSON)')),
                ('current_status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('SUBMITTED', 'Soumise / À valider'), ('VALIDATED', 'Validée')], default='SCHEDULED', max_length=20, verbose_name='Statut de la visite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visite active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='inspections.inspectionfolder', verbose_name='Dossier associé')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_visits', to=settings.AUTH_USER_MODEL, verbose_name='Inspecteur terrain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_visits', to=settings.AUTH_USER_MODEL, verbose_name='Modifié en dernier par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='inspections.visittemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Instance de visite',
                'verbose_name_plural': 'Instances de visite',
                'ordering': ['-created_at'],
            },
        ),
    ]
