# Generated by Django 6.0.6 on 2026-07-06 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectionfolder_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitinstance',
            name='owner',
        ),
        migrations.AddField(
            model_name='visittemplate',
            name='shared',
            field=models.BooleanField(default=False, verbose_name='Partagé avec tous les utilisateurs'),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(verbose_name='Description de la recommandation')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20, verbose_name='Priorité')),
                ('current_status', models.CharField(choices=[('OPEN', 'Ouverte'), ('IN_PROGRESS', 'En cours'), ('RESOLVED', 'Résolue'), ('ABANDONED', 'Abandonnée')], default='OPEN', max_length=20, verbose_name='Statut actuel')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date limite d'exécution")),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='inspections.inspectionfolder', verbose_name="Dossier d'inspection")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Modifié en dernier par')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['due_date', '-priority'],
                'abstract': False,
            },
        ),
    ]
