# Generated by Django 6.0.6 on 2026-07-06 21:12

import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_remove_visitinstance_owner_visittemplate_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitinstance',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de visite'),
        ),
        migrations.AlterField(
            model_name='visitinstance',
            name='current_status',
            field=models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'A venir'), ('DELAY', 'En retard'), ('VALIDATED', 'Effectuée')], default='SCHEDULED', max_length=20, verbose_name='Statut de la visite'),
        ),
        migrations.AlterField(
            model_name='visittemplate',
            name='schema',
            field=models.JSONField(default=inspections.models.get_default_template_structure, verbose_name='Structure du template (JSON)'),
        ),
    ]
