# Generated by Django 6.0.6 on 2026-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_visitinstance_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitinstance',
            name='current_status',
            field=models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('DELAY', 'En retard'), ('VALIDATED', 'Effectuée')], default='SCHEDULED', max_length=20, verbose_name='Statut de la visite'),
        ),
    ]
