# Generated by Django 6.0.6 on 2026-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_visitinstance_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionfolder',
            name='inspection_site_address',
            field=models.TextField(blank=True, verbose_name="Adresse du site d'inspection"),
        ),
        migrations.AddField(
            model_name='inspectionfolder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sujet de la recommandation'),
        ),
        migrations.AddField(
            model_name='visitinstance',
            name='instance_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name="Structure de l'instance (JSON)"),
        ),
    ]
