# Generated by Django 6.0.6 on 2026-07-10 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectionfolder_inspection_site_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfolder',
            name='reference',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_reference_structure', message="La référence doit respecter le format 'RF-YYYY-0000' (ex: RF-2026-0412).", regex='^RF-\\d{4}-\\d{4}$')], verbose_name='Référence du dossier'),
        ),
    ]
