# Generated by Django 6.0.6 on 2026-07-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_inspectionfolder_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionfolder',
            name='current_phase',
            field=models.CharField(choices=[('CREATION', 'En création'), ('IN_PROGRESS', 'Dossier en cours'), ('REVIEW', 'En cours de revue'), ('COMPLETED', 'Terminé / Clôturé'), ('ARCHIVED', 'Archivé')], default='CREATION', max_length=20, verbose_name='Phase actuelle'),
        ),
        migrations.AlterField(
            model_name='inspectionfolder',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Référence du dossier'),
        ),
    ]
