# Generated by Django 6.0.6 on 2026-07-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_company_executive_board_alter_company_labels_and_more'),
        ('inspections', '0008_alter_inspectionfolder_current_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionfolder',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_folders', to='crm.contact', verbose_name='Contact référent'),
        ),
        migrations.AddField(
            model_name='recommandation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes sur la recommandation'),
        ),
        migrations.AddField(
            model_name='visitinstance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes sur la visite'),
        ),
        migrations.AlterField(
            model_name='inspectionfolder',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Référence du dossier'),
        ),
    ]
